// Clean Local Database - Preserve Core Data Only
// Usage: mongosh mongodb://localhost:27017 < clean_local_db.js
// 
// This script:
// 1. Backs up core data (users, trading_accounts, market_hours, market_holidays)
// 2. Drops all transactional collections
// 3. Resets trading accounts (blockedMargin = 0, realizedPL = 0)
// 4. Restores core data
// 5. Drops instruments and market_data (will be regenerated)

db = db.getSiblingDB('aequitas');

print("╔════════════════════════════════════════════════════════════╗");
print("║   CLEAN LOCAL DATABASE - PRESERVE CORE DATA                ║");
print("╚════════════════════════════════════════════════════════════╝");
print("");
print("Started at:", new Date());
print("");

// Step 1: Backup core data
print("┌─────────────────────────────────────────────────────────┐");
print("│ Step 1: Backing up core data                            │");
print("└─────────────────────────────────────────────────────────┘");

const users = db.users.find().toArray();
const tradingAccounts = db.trading_accounts.find().toArray();
const marketHours = db.market_hours.find().toArray();
const marketHolidays = db.market_holidays.find().toArray();

print("  ✓ Backed up", users.length, "users");
print("  ✓ Backed up", tradingAccounts.length, "trading accounts");
print("  ✓ Backed up", marketHours.length, "market hours");
print("  ✓ Backed up", marketHolidays.length, "market holidays");
print("");

// Step 2: Drop ALL collections (including instruments)
print("┌─────────────────────────────────────────────────────────┐");
print("│ Step 2: Dropping all collections                        │");
print("└─────────────────────────────────────────────────────────┘");

const allCollections = [
    'holdings',
    'orders',
    'trades',
    'portfolio_snapshots',
    'notifications',
    'instruments',      // Will be regenerated from production
    'market_data',      // Will be regenerated by pricing engine
    'candles',          // Will be regenerated by pricing engine
    'users',            // Will restore from backup
    'trading_accounts', // Will restore from backup (reset)
    'market_hours',     // Will restore from backup
    'market_holidays'   // Will restore from backup
];

allCollections.forEach(function (collName) {
    try {
        db[collName].drop();
        print("  ✓ Dropped", collName);
    } catch (e) {
        print("  ⚠️  Could not drop", collName, "(may not exist)");
    }
});
print("");

// Step 3: Reset trading accounts
print("┌─────────────────────────────────────────────────────────┐");
print("│ Step 3: Resetting trading accounts                      │");
print("└─────────────────────────────────────────────────────────┘");

// Reset blockedMargin and realizedPL for all accounts
tradingAccounts.forEach(function (account) {
    account.blockedMargin = 0;
    account.realizedPL = 0;
    account.updatedAt = new Date();
});

if (tradingAccounts.length > 0) {
    db.trading_accounts.insertMany(tradingAccounts);
    print("  ✓ Reset", tradingAccounts.length, "trading accounts");
    print("    • blockedMargin = 0");
    print("    • realizedPL = 0");
}
print("");

// Step 4: Restore core data
print("┌─────────────────────────────────────────────────────────┐");
print("│ Step 4: Restoring core data                             │");
print("└─────────────────────────────────────────────────────────┘");

// Users
if (users.length > 0) {
    db.users.insertMany(users);
    print("  ✓ Restored", users.length, "users");
}

// Market hours
if (marketHours.length > 0) {
    db.market_hours.insertMany(marketHours);
    print("  ✓ Restored", marketHours.length, "market hours");
}

// Market holidays
if (marketHolidays.length > 0) {
    db.market_holidays.insertMany(marketHolidays);
    print("  ✓ Restored", marketHolidays.length, "market holidays");
}
print("");

// Step 5: Create indexes
print("┌─────────────────────────────────────────────────────────┐");
print("│ Step 5: Creating indexes                                │");
print("└─────────────────────────────────────────────────────────┘");

// Users
db.users.createIndex({ email: 1 }, { unique: true });
print("  ✓ users.email (unique)");

// Trading Accounts
db.trading_accounts.createIndex({ user_id: 1 }, { unique: true });
print("  ✓ trading_accounts.user_id (unique)");

// Holdings
db.holdings.createIndex({ user_id: 1, instrument_id: 1 }, { unique: true });
print("  ✓ holdings.user_id + instrument_id (unique)");

// Orders
db.orders.createIndex({ user_id: 1, created_at: -1 });
db.orders.createIndex({ status: 1 });
print("  ✓ orders.user_id + created_at");
print("  ✓ orders.status");

// Instruments
db.instruments.createIndex({ symbol: 1 }, { unique: true });
print("  ✓ instruments.symbol (unique)");

print("");

// Step 6: Summary
print("╔════════════════════════════════════════════════════════════╗");
print("║   CLEANUP SUMMARY                                          ║");
print("╚════════════════════════════════════════════════════════════╝");
print("");
print("✅ Core data preserved:");
print("  • Users:", db.users.countDocuments());
print("  • Trading Accounts:", db.trading_accounts.countDocuments());
print("  • Market Hours:", db.market_hours.countDocuments());
print("  • Market Holidays:", db.market_holidays.countDocuments());
print("");
print("✅ Transactional data cleared:");
print("  • Holdings: 0");
print("  • Orders: 0");
print("  • Trades: 0");
print("  • Instruments: 0 (sync from production)");
print("  • Market Data: 0 (will be generated)");
print("  • Candles: 0 (will be generated)");
print("");
print("Completed at:", new Date());
print("");
print("╔════════════════════════════════════════════════════════════╗");
print("║   NEXT STEPS                                               ║");
print("╚════════════════════════════════════════════════════════════╝");
print("");
print("1. Copy instruments from production:");
print("   Use MongoDB Compass to export/import instruments collection");
print("   OR run seed_instruments.go against localhost");
print("");
print("2. Start local backend:");
print("   go run cmd/server/main.go");
print("");
print("3. Pricing engine will auto-generate market data");
print("");
print("✅ Local database cleaned!");
